### ISSUE TITLE
Specify licence

### ISSUE THREAD

**Issue by tindzk** [ABRG-Models/morphologica#10]
Currently, the repository does not specify a licence. The authors' copyright is therefore not protected. I suggest to choose an open source licence and add the corresponding `LICENSE` file.

**Further reading:**
- https://www.gov.uk/government/publications/protecting-your-uk-intellectual-property-abroad/protecting-your-copyright-abroad
- https://choosealicense.com/
- https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by sebjameswml** [comment]
I've added a LICENSE file. The headers in the code could do with modifying to mention the licence, too.

**Comment by tindzk** [comment]
How about choosing a more permissive licence like Apache 2.0 or MIT? GPL will prevent developers from building closed-source programs based on morphologica. Along with the linked artefacts, developers would have to distribute the entire source code which may be undesirable. See also [this link](https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application).

**Comment by sebjameswml** [comment]
The GPL is the right licence in my opinion. This code is not intended for
commercial applications.

**Comment by tindzk** [comment]
Okay, thanks for the clarification.
