### ISSUE TITLE
Segmentation fault while trying to make a continuously updating scatter plot

### ISSUE THREAD

**Issue by Stack-it-up** [ABRG-Models/morphologica#115]
Hello, 
I'm very new to the library so sorry if the question is silly but after spending some hours on this problem I can't seem to find a solution.

I've been trying to make an updating scatterplot. The example ``scatter.cpp`` works fine for me, but after making the following modifications I always get a segmentation fault before the plot even manages to show up for the first iteration.

<details>
<summary> open spoiler to show the code </summary>
  
```
  /*
   * Visualize a test surface
   */
  #include <morph/Visual.h>
  #include <morph/ColourMap.h>
  #include <morph/ScatterVisual.h>
  #include <morph/Scale.h>
  #include <morph/vec.h>
  #include <morph/vvec.h>
  #include <iostream>
  #include <fstream>
  #include <cmath>
  #include <array>
  #include <iostream>
  int main (int argc, char** argv)
  {
      int rtn = -1;
      morph::Visual v(848, 480, "morph::ScatterVisual", {0,0}, {1,1,1}, 1.0f, 0.05f);
      v.zNear = 0.001;
      v.showCoordArrows = true;
      v.coordArrowsInScene = true;
      v.showTitle = true;
      // Blueish background:
      v.bgcolour = {0.6f, 0.6f, 0.8f, 0.5f};
      v.lightingEffects();
      morph::vec<float, 3> offset = { 0.0, 0.0, 0.0 };
      morph::Scale<float> scale;
      scale.setParams (1.0, 0.0);
      auto sv = std::make_unique<morph::ScatterVisual<float>> (v.shaders, offset);
      v.addVisualModel (sv);
      morph::vvec<morph::vec<float, 3>> points(20*20);
      morph::vvec<float> data(20*20);
      for(int q=0; q<100; q++) {
          std::cout << q << std::endl;
          if(v.readyToFinish)
              break;
          size_t k = 0;
          for (int i = -10; i < 10; ++i) {
              for (int j = -10; j < 10; ++j) {
                  float x = 0.1*i + 0.1;
                  float y = 0.1*j;
                  // z is some function of x, y
                  float z = 0.1*q * x * std::exp(-(x*x) - (y*y));
                  points[k] = {x, y, z};
                  data[k] = z;
                  k++;
              }
          }
          sv->setDataCoords (&points);
          sv->setScalarData (&data);
          sv->radiusFixed = 0.03f;
          sv->colourScale = scale;
          sv->cm.setType (morph::ColourMapType::Plasma);
          sv->finalize();
          //sv->updateCoords (&points);
          //sv->updateData (&data);
          //sv->updateScalar(&data);
          glfwWaitEventsTimeout (0.1);
          v.render();
          std::cout << "render finished" << std::endl;
      }
      return rtn;
  }
  ```

</details>

Any idea about what I might be doing wrong?

I also tried with updateData() and updateCoords() but the effect is the same.

Output:
```
0
Segmentation fault (core dumped)
```

GDB reports that the segfault is at the instruction ``sv->setDataCoords (&points);``

**Comment by Stack-it-up** [comment]
Reading up on the matter, could it be an instance of the issues mentioned here with extending STL containers?
https://stackoverflow.com/questions/2034916/is-it-okay-to-inherit-implementation-from-stl-containers-rather-than-delegate

**Comment by sebjameswml** [comment]
Hi, from a quick look, it looks like the order of your operations on the ScatterVisual isn't the 'designed' way. However, I've fixed this and I get a crash too!

I've implemented dynamic versions of my other classes, such as the QuiverVisual. I'll come back to you when I've got a fixed example of a dynamic ScatterVisual.

Seb

**Comment by sebjameswml** [comment]
Here's a working example.

As I mentioned, there was an issue with ordering. Here, you'll see I set up the ScatterVisual with std::make_unique, and then add it to the morph::Visual.

When you add the unique_ptr object to the Visual, Visual takes ownership, which means you can no longer call functions with the unique_ptr. So, after you  addVisualModel(), you have to use the plain, non-owning pointer that addVisualModel returns to interact with your ScatterVisual. Any attempt to use the original unique_ptr will result in a crash.

Also note that the only thing we have to do in the loop to update the model is call its reinit() function. Because you changed the data in points/data on each loop, the model gets completely rebuilt with the new positions.

```C++
/*
 * Visualize a test surface
 */
#include <morph/Visual.h>
#include <morph/ColourMap.h>
#include <morph/ScatterVisual.h>
#include <morph/Scale.h>
#include <morph/vec.h>
#include <morph/vvec.h>
#include <iostream>
#include <fstream>
#include <cmath>
#include <array>
#include <iostream>
int main (int argc, char** argv)
{
    int rtn = -1;
    morph::Visual v(848, 480, "morph::ScatterVisual", {0,0}, {1,1,1}, 1.0f, 0.05f);
    v.zNear = 0.001;
    v.showCoordArrows = true;
    v.coordArrowsInScene = true;
    v.showTitle = true;
    // Blueish background:
    v.bgcolour = {0.6f, 0.6f, 0.8f, 0.5f};
    v.lightingEffects();
    morph::vec<float, 3> offset = { 0.0, 0.0, 0.0 };
    morph::Scale<float> scale;
    scale.setParams (1.0, 0.0);
    auto sv = std::make_unique<morph::ScatterVisual<float>> (v.shaders, offset);
    // So the initial set up:
    morph::vvec<morph::vec<float, 3>> points(20*20);
    morph::vvec<float> data(20*20);
    sv->setDataCoords (&points);
    sv->setScalarData (&data);
    sv->radiusFixed = 0.03f;
    sv->colourScale = scale;
    sv->cm.setType (morph::ColourMapType::Plasma);
    // Finalize (build the model and add to the Visual), even though there's no data or points to show yet
    sv->finalize();
    auto svp = v.addVisualModel (sv); // When you add the model to the Visual, it takes
                                      // ownership of the memory and returns a pointer
                                      // that you can use (svp). svp is of type morph::ScatterVisual<float>*

    for(int q=0; q<100; q++) {
        if(v.readyToFinish) { break; }
        size_t k = 0;
        for (int i = -10; i < 10; ++i) {
            for (int j = -10; j < 10; ++j) {
                float x = 0.1*i + 0.1;
                float y = 0.1*j;
                // z is some function of x, y
                float z = 0.1*q * x * std::exp(-(x*x) - (y*y));
                points[k] = {x, y, z};
                data[k] = z;
                k++;
            }
        }

        // On each loop, just call VisualModel::reinit(). This re-builds the OpenGL model using the now changed content of 'points' and 'data'
        svp->reinit();

        glfwWaitEventsTimeout (0.1);
        v.render();
    }
    return rtn;
}

```

**Comment by sebjameswml** [comment]
I've added scatter_dynamic.cpp as a new example; see 52f16fa

**Comment by sebjameswml** [comment]
> Reading up on the matter, could it be an instance of the issues mentioned here with extending STL containers? https://stackoverflow.com/questions/2034916/is-it-okay-to-inherit-implementation-from-stl-containers-rather-than-delegate

This was nothing to do with the issue you had. From the stackoverflow you referenced:

_The risk is deallocating through a pointer to the base class (delete, delete[], and potentially other deallocation methods). Since these classes (deque, map, string, etc.) don't have virtual dtors, it's impossible to clean them up properly with only a pointer to those classes:_

```C++
struct BadExample : vector<int> {};
int main() {
  vector<int>* p = new BadExample();
  delete p; // this is Undefined Behavior
  return 0;
}
```

_That said, if you're willing to make sure you never accidentally do this, there's little major drawback to inheriting them—but in some cases that's a big if_

So, I take this risk with morph::vvec and morph::vec. It's worth it in my opinion, because the benefit of a maths-specific vector class is huge convenience.

**Comment by Stack-it-up** [comment]
Hi and thank you for the answer! I'm afk at the moment but I'll reply properly as soon as I get back on Tuesday.

9 lug 2023 11:26:59 Seb James ***@***.***>:

**Comment by Stack-it-up** [comment]
Hello @sebjameswml 

Thank you for looking into my code, I have tried the new example and it works correctly on my setup!

All the best

**Comment by optseb** [comment]
Great, glad that worked for you too! Hope you find the code useful. Feel free to post any other queries you have here, and I'll do my best to help.
