### ISSUE TITLE
Updating a visual model containing text can fail if GLFW context is not available

### ISSUE THREAD

**Issue by optseb** [ABRG-Models/morphologica#127]
In the current, non-qt branch the Fonts are obtained using the GLFW window id as part of a key into an `std::map`. In the main branch at the time of writing, the GLFW window id is obtained with `glfwGetCurrentContext()`, which may return 0x0 if there is  no window context. We ran into this with drawing windows within a ros2 program. Happily, the indexing system has been redesigned in soon-to-be-merged code in branch 
**/redesign/qtcompatibility**

**Comment by sebjameswml** [comment]
You fix this by calling Visual::setContext() when you need the context to be available.
