### ISSUE TITLE
This project can run under Windows with msys2 and gcc

### ISSUE THREAD

**Issue by asmwarrior** [ABRG-Models/morphologica#152]
Hi, I have just tried this project. Looks good!

I'm testing a very simple hello world project under: Windows 10, Code::Blocks IDE, msys2.
Note that msys2 supplied many packages, include: freetype, glfw3, flew, opencv.

Here is the screen shot:

![image](https://github.com/ABRG-Models/morphologica/assets/561818/a0cdef94-a21f-4c73-91c0-e7e8cba448b8)

I'm not good at CMake, I can only supply Code::Blocks project files.

**Comment by asmwarrior** [comment]
![image](https://github.com/ABRG-Models/morphologica/assets/561818/f2c27ae6-97a7-4902-90ad-54f40084a67c)


The above image is my another test to run the test file: `examples\graph1.cpp`.

When I start the program, an ampty window will first pop up, and I need to wait a few seconds to see the actual graph inside the window, I'm not sure this is by design, I see it also happens in the "hello world" sample code.

**Comment by asmwarrior** [comment]
I see an error message in the console window, see below:

![image](https://github.com/ABRG-Models/morphologica/assets/561818/6fe8cfb4-ca82-4c25-9629-5331c88c82cc)

This message happens in many test cases.

**Comment by sebjameswml** [comment]
Hi! Thanks for experimenting with the code on Windows. I'm glad you had some success.

The delays you report between window and graphics are not expected, so that's definitely an issue. I wonder what's happening... 

The error about failing to make the context current may well be related. you could experiment with Visual::setContext - perhaps theres a short time with this platform during which the GL env is not ready.

**Comment by sebjameswml** [comment]
Would you like to contribute build instructions for msys2?

**Comment by asmwarrior** [comment]
I can help, but I'm not good at cmake. In-fact, I'm good at Code::Blocks.

I have a change to my fork: [under msys2+gcc, I have to comment out the header files, because I have no such header files, but the build still look OK](https://github.com/asmwarrior/morphologica/commit/60566fd68691998f02f9eefa1d6e03f8d2c01aef)

With this change, I can build your project under msys2 and mingw64 gcc.

Also, here is the Code::Blocks cbp file content:

~~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<CodeBlocks_project_file>
	<FileVersion major="1" minor="6" />
	<Project>
		<Option title="glfwtest" />
		<Option pch_mode="2" />
		<Option compiler="gcc" />
		<Build>
			<Target title="Debug">
				<Option output="bin/Debug/glfwtest" prefix_auto="1" extension_auto="1" />
				<Option object_output="obj/Debug/" />
				<Option type="1" />
				<Option compiler="gcc" />
				<Compiler>
					<Add option="-g" />
				</Compiler>
			</Target>
			<Target title="Release">
				<Option output="bin/Release/glfwtest" prefix_auto="1" extension_auto="1" />
				<Option object_output="obj/Release/" />
				<Option type="1" />
				<Option compiler="gcc" />
				<Compiler>
					<Add option="-O2" />
				</Compiler>
				<Linker>
					<Add option="-s" />
				</Linker>
			</Target>
		</Build>
		<Compiler>
			<Add option="-Wall" />
			<Add option="-fexceptions" />
			<Add option="-DUSE_GLEW" />
			<Add option="-D__WIN__" />
			<Add directory="F:/code/morphologica/" />
			<Add directory="F:/msys2/mingw64/include/freetype2/" />
			<Add directory="F:/code/morphologica/include" />
		</Compiler>
		<Linker>
			<Add option="`pkg-config --libs glm`" />
			<Add option="`pkg-config --libs glfw3`" />
			<Add option="`pkg-config --libs glew`" />
			<Add option="`pkg-config --cflags freetype2`" />
			<Add library="opengl32" />
			<Add library="freetype" />
		</Linker>
		<Unit filename="main.cpp" />
		<Extensions />
	</Project>
</CodeBlocks_project_file>
~~~~

You can see the include paths in the cbp file.
