### ISSUE TITLE
key value issue in wx/keycodes.h

### ISSUE THREAD

**Issue by asmwarrior** [ABRG-Models/morphologica#162]
`a` should be `A`, see the document here:

https://docs.wxwidgets.org/trunk/classwx_key_event.html

https://github.com/ABRG-Models/morphologica/blob/0df9345d71c4063ab5731ba97a3bc0c676b4c8d6/morph/wx/keycodes.h#L71-L73

**Comment by sebjameswml** [comment]
Thanks for spotting that one and letting me know. The correction is in b3e38ff
