### ISSUE TITLE
Qt `viswidget` doesn't handle high DPI displays

### ISSUE THREAD

**Issue by GeoSpark** [ABRG-Models/morphologica#192]
Qt uses device-independent pixels when reporting window geometry, but uses physical pixels for `QOpenGLWidget` https://doc.qt.io/qt-6/highdpi.html
A simple fix in `viswidget.h` could be:
```
        void resizeGL(int w, int h) {
            double dpr = this->devicePixelRatio();
            v.set_winsize(static_cast<int>(w * dpr), static_cast<int>(h * dpr));
            this->update();
        }
```

This has only been tested on Linux, and only at integer multiples of the native display resolution. Non-integer scaling may require rounding to avoid off-by-one problems.

**Comment by sebjameswml** [comment]
Ah great. Thanks for this. There's a fragment of code somewhere , maybe just a comment, that talks about this wrt high dpi Displays on Mac. I'll incorporate this into the viswidget example.

**Comment by sebjameswml** [comment]
I've made that change. I stuck in a call to std::round to handle non-integer devicePixelRatio() return values.
