### ISSUE TITLE
histo<int> won't graph with GraphVisual<int>

### ISSUE THREAD

**Issue by optseb** [ABRG-Models/morphologica#213]
You get a problem within morph::Scale

**Comment by optseb** [comment]
To reproduce, rewrite randvec.cpp example with ints

**Comment by sebjameswml** [comment]
histo<int> is now hist<int, float> where int is for the histogrammed data and float is for the proportions computed (bin widths etc). histo<int> is the same as histo<int, float> and both would be graphed with GraphVisual<float>.
