### ISSUE TITLE
Decide what to do about Grid::n

### ISSUE THREAD

**Issue by optseb** [ABRG-Models/morphologica#285]
Grid has a member, `n`, which is `w` x `h`. I forgot it was there when @blenk13 and I put in `Grid::get_n_pixels`. `n` is used in `Grid::operator[]`.

Would either like `get_n_pixels()` to be `n()` or for `n` to be private and for `get_n_pixels` (renamed `get_n`) to be a getter. Profile operator[] in both cases to see if either one is appreciably slower.

**Comment by sebjameswml** [comment]
Profiling indicated no difference between using a member attribute `I n` or `I n() { return w * h; }`
