### ISSUE TITLE
Consider making build of tests/examples explicit

### ISSUE THREAD

**Issue by niclar** [ABRG-Models/morphologica#43]
Tying to build an example. -The cmake installation target for morph seem to miss e.g. Visual.h, ScatterVisual.h

**Comment by sebjameswml** [comment]
This might have happened if you built and installed morphologica without first having installed the glfw library on your system. If the cmake process fails to find glfw, then a `make install` won't install `Visual.h` and all the other headers required for graphical programs. Here's the relevant section of the CMakeLists.txt: https://github.com/ABRG-Models/morphologica/blob/main/morph/CMakeLists.txt#L16

**Comment by sebjameswml** [comment]
I'm just trying to build standalone_examples/schnakenberg with an installed morphologica (installed into /usr/local/). There *are* one or two headers that are not installed - base64.h is one.

**Comment by niclar** [comment]
Yeah I tried building morph in isolation omitting examples & tests. 

-Can you maybe make dependencies and examples explicitly optional (from the top level cmake) ?

**Comment by sebjameswml** [comment]
Making deps and examples explicitly optional is possible, so that it's a simple make && make install process (buildling all the tests and examples does take quite a while).

**Comment by sebjameswml** [comment]
I don't think I'll change the build process. When you type make, you'll just get all the tests and examples compiled.
