### ISSUE TITLE
replace __WIN__ with WIN32

### ISSUE THREAD

**Issue by niclar** [ABRG-Models/morphologica#46]
-Would you consider replacing the "__WIN__" define with the standard "WIN32" instead ?

**Comment by sebjameswml** [comment]
I would consider this. However, I'm not very knowledgeable about Windows. A quick google suggests that WIN32 is defined whether you're compiling 32 or 64 bit Windows. Right? Is it safe to use the WIN32 definition as just meaning "this is Windows" and you have to use an alternative test if you want to determine whether it's a 32 or 64 bit compilation?

**Comment by niclar** [comment]
Yes WIN32 is defined for both so that's the pragmatic way

**Comment by sebjameswml** [comment]
I'm thinking about this one. Right now I have a scheme where I use cmake to probe the host OS and then I define a tag accordingly. What you suggest is pragmatic, and means that the code could be used on Windows without the developer needing to define an extra label when calling their compiler, but if I were to make the change, then I should consider whether to use #ifdef __APPLE__ on MacOS and what I should do on Linux/BSD.

**Comment by sebjameswml** [comment]
I am happy with using __WIN__ as a tag for Windows.
