### ISSUE TITLE
include\morph/VisualFace.h(198,76): error C2065: 'vf_dvsansData': undeclared identifier

### ISSUE THREAD

**Issue by niclar** [ABRG-Models/morphologica#48]
Building under windows vf_dvsansData etc. is undeclared for some reason.

1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(198,76): error C2065: 'vf_dvsansData': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(198,91): error C2065: 'vf_dvsansEnd': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(204,76): error C2065: 'vf_dvsansitData': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(204,93): error C2065: 'vf_dvsansitEnd': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(210,76): error C2065: 'vf_dvsansbdData': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(210,93): error C2065: 'vf_dvsansbdEnd': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(216,76): error C2065: 'vf_dvsansbiData': undeclared identifier
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(216,93): error C2065: 'vf_dvsansbiEnd': undeclared identifier

**Comment by sebjameswml** [comment]
Ok, I think that's because when I made morphologica work on Windows, it was before I later introduced the DejaVu font (which I did so that I could render a wide variety of characters).

The use of a header file containing the fonts is only necessary on Windows, but to date, I've not created an equivalent to verafonts.h for the DejaVu font.

**Comment by sebjameswml** [comment]
(it's not a terribly difficult job though)

**Comment by niclar** [comment]
standing by then ;)

**Comment by sebjameswml** [comment]
This should be fixed with bd2dfbc

**Comment by niclar** [comment]
thanks
