### ISSUE TITLE
compilation error: use of deleted stream operator for char32_t

### ISSUE THREAD

**Issue by niclar** [ABRG-Models/morphologica#49]
conformant implementations won't allow ostream << char32_t   

template< class Traits >
basic_ostream<char,Traits>& operator<<( basic_ostream<char,Traits>& os,
                                        char32_t ch ) = delete;
  

>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(399,80): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,char32_t)': attempting to reference a deleted function
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.32.31114\include\ostream(967): message : see declaration of 'std::operator <<'
1>C:\src\thirdparty\vcpkg\installed\x64-windows-static\include\morph/VisualFace.h(399,80): error C2088: '<<': illegal for class

**Comment by sebjameswml** [comment]
44b3672 provides a proper fix.
