### ISSUE TITLE
multi threaded updates

### ISSUE THREAD

**Issue by niclar** [ABRG-Models/morphologica#50]
How would one update e.g the ScatterVisual with real time data points from another thread ?

I see that the Vector class is not thread safe ...

I suspect it's to be handled by the user right ? Like pulling a thread safe queue from the render loop updating the ScatterVisual 
 Vector (pop_back and push_front)..

**Comment by sebjameswml** [comment]
Yes, up to the user. In the applications that have been written to date (ABRG-Models/BarrelEmerge, sebjameswml/RetinoTectal, ABRG-Models/Tesselations, stuartwilson/SelfOrganisingMaps) the usual approach is to compute a timestep of a simulation or model in each iteration of a main loop and then to update/render the visual model at every Nth loop. Depending on the sim, that might be every single loop, every 10th, 100th or whatever suits. We haven't used multithreading to run a simulation/model in one thread with a second thread used for visualisation. I personally make use of multithreading within my simulations, using OpenMP pragmas - I find that's the best way to get the most out of multi-core CPUs.

What makes you think that the Vector class is not thread safe?

**Comment by niclar** [comment]
Yes, keeping threading external makes sense. In my case it's a real-time visualization of high frequency data so keeping a separate render loop is more appropriate.
-The underlying data structure of the Vector class is a std::array which if misaligned is subject to write tearing. 
(Further the atomic read/write assumption (guaranteed on x86/x64) should probably be asserted if the Vector was to be used in a multi threaded context)
