### ISSUE TITLE
Consider thread safety of Vector (and vVector) classes

### ISSUE THREAD

**Issue by sebjameswml** [ABRG-Models/morphologica#52]
@niclar writes: "The underlying data structure of the Vector class is a std::array which if misaligned is subject to write tearing.
(Further the atomic read/write assumption (guaranteed on x86/x64 for the fundamental datatypes, int, double..) should probably be asserted if the Vector was to be used in a multi threaded context)"

**Comment by niclar** [comment]
-One might argue that since you leave all threading up to the user it's their responsibility to ensure the above.

**Comment by sebjameswml** [comment]
Useful info on std::atomic: https://stackoverflow.com/questions/31978324/what-exactly-is-stdatomic

**Comment by sebjameswml** [comment]
These are as thread safe as std::array or std::vector. Closing.
