### ISSUE TITLE
ScatterVisual diffrent radiuses

### ISSUE THREAD

**Issue by niclar** [ABRG-Models/morphologica#53]
-Is there a way to plot different radiuses for the points in a scatter visual (instead of in different colors) ?

**Comment by sebjameswml** [comment]
Not sure that I've coded in a way to plot different sized points all at once for a complete dataset - you could think about hacking that in. 

I HAVE used different sized blobs, though, there's a `ScatterVisual::add` method that allows you to specify the radius of each point as they're added one by one.

**Comment by niclar** [comment]
-Apparently you did..  one sets sizeFactor instead of radiusFixed  :)
